# Generated by Django 5.0.1 on 2024-01-11 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='is_email_verfied',
            new_name='is_email_verified',
        ),
    ]
